//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Zhurikhin_AutoDealer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deals
    {
        public int DealID { get; set; }
        public string VIN { get; set; }
        public int ClientID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime DealDate { get; set; }
        public decimal FinalPrice { get; set; }
        public string ContractStatus { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
