//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Zhurikhin_AutoDealer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryParts
    {
        public int DeliveryPartID { get; set; }
        public int DeliveryID { get; set; }
        public int PartID { get; set; }
        public int Quantity { get; set; }
        public decimal PurchasePrice { get; set; }
    
        public virtual Deliveries Deliveries { get; set; }
        public virtual Parts Parts { get; set; }
    }
}
