//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Zhurikhin_AutoDealer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderWorks
    {
        public int OrderWorkID { get; set; }
        public int OrderID { get; set; }
        public int ServiceID { get; set; }
        public int EmployeeID { get; set; }
        public decimal FactHours { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual ServiceOrders ServiceOrders { get; set; }
        public virtual Services Services { get; set; }
    }
}
