//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Zhurikhin_AutoDealer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderParts
    {
        public int OrderPartID { get; set; }
        public int OrderID { get; set; }
        public int PartID { get; set; }
        public int Quantity { get; set; }
        public decimal PriceAtMoment { get; set; }
    
        public virtual ServiceOrders ServiceOrders { get; set; }
        public virtual Parts Parts { get; set; }
    }
}
